apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jwt-demo-app.fullname" . }}
  labels: {{- include "jwt-demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "jwt-demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "jwt-demo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000